version: '2'

services:
  server:
    build: server
    ports:
     - "0.0.0.0:3000:3000"
    depends_on:
      - rabbitmq
      - redis
    environment:
      RABBITMQ_URL:    'amqp://rabbitmq'
      CABLE_REDIS_URL: 'redis://redis:6379/1'
    command: bash -c 'sleep 5; bundle exec rails server --bind 0.0.0.0'

  rabbitmq:
    build: rabbitmq
    ports:
     - "15672:15672" # RabbitMQ management web console
     - "15674:15674" # WebStomp endpoint (WebSocket and SockJS)

  redis:
    image: redis
