# Action Cable uses Redis by default to administer connections, channels, and sending/receiving messages over the WebSocket.
common: &common
  adapter: redis
  url: <%= ENV.fetch('CABLE_REDIS_URL') { 'redis://localhost:6379/1' } %>

production:
  <<: *common

development:
  <<: *common

test:
  adapter: async
